import type { Metadata } from "next";
import { notoSans, roboto, raleway } from "@/app/ui/fonts";
import Loading from "@/app/ui/Loading";
// import "@/app/ui/globals.css";
import "../../public/css/style.css";
import clsx from "clsx";
import Header from "@/app/ui/Header";
import Footer from "@/app/ui/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={notoSans.className}>
        <div id="wrapper">
          <Header />
          <main className="page-main">{children}</main>
          <Footer />
        </div>
        {/* <Loading /> */}
      </body>
    </html>
  );
}
